name: "WiNet Extractor"
description: "Extracts data from WiNet devices and sends to Home Assistant over MQTT."
version: "0.1.0"
stage: "stable"
slug: "winet-extractor"
url: "https://github.com/NickStallman/Winet-Extractor/"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
map:
  - config:rw
panel_icon: mdi:solar-power
auth_api: false
hassio_role: "admin"
hassio_api: true
homeassistant_api: true
startup: "application"
init: false
services:
  - mqtt:need

options:
  winet_host: ""
  mqtt_url: ""

schema:
  winet_host: str?
  mqtt_url: str